Updates language standards to include specification for GraphQL documentation.
qctrl/.github pull request #20
Opened 2020-09-03 01:05 UTC by TabishB

Changes proposed in this pull request:

- Specifies CommonMark as the standard for GraphQL documentation.
- Adds information about the additional syntax used on top of the CommonMark syntax.

2020-09-03 01:11 UTC, charmasaur requested changes
Looks good, thanks Tabish!

2020-09-03 01:11 UTC, charmasaur commented on CONTRIBUTING.md
> +In most cases we try and follow the Markdown syntax as specified by [CommonMark](http://commonmark.org/) which is the standard adopted and reccomended by GraphQL . Unfortunately the CommonMark specif
```suggestion
In most cases we try and follow the Markdown syntax as specified by [CommonMark](http://commonmark.org/) which is the standard adopted and recommended by GraphQL. Unfortunately the CommonMark specification does not cover all of our use cases, as we use the docstrings to document our client-side functions and not just the API. We therefore have these additional custom specifications in place:
```

2020-09-03 01:32 UTC, charmasaur submitted a review, later dismissed

2020-09-03 01:40 UTC, leoadec reviewed
Thanks for this, it's quite useful to have this additional information available somewhere.

One minor comment about style is that the MS Style Guide recommends using more "you" and less "we" (for example, writing "follow these standards" instead of "we follow these standards"—see https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/we ), but I'm not sure how consistently we've been applying it to these Guidelines

2020-09-03 01:40 UTC, leoadec commented on CONTRIBUTING.md
> +For more information and examples on how we use GraphQL docstrings for documenting core features and functions in the api, follow the [link](https://github.com/qctrl/api2#writing-documentation-for-co
As the .github repo is public, I don't know if we usually link to private repositories from here. If we do, we might want to set "the relevant section in the api2 documentation" as the link text, to keep it meaningful (see the 6th item of https://docs.microsoft.com/en-us/style-guide/accessibility/writing-all-abilities#write-brief-meaningful-and-focused-text)

2020-09-03 03:33 UTC, TabishB commented on CONTRIBUTING.md
> +For more information and examples on how we use GraphQL docstrings for documenting core features and functions in the api, follow the [link](https://github.com/qctrl/api2#writing-documentation-for-co
Hmm you're right, since this is a public repo I'm not sure if it should even mention core features and functions to be honest.

2020-09-16 08:03 UTC, TabishB commented on CONTRIBUTING.md
> +For more information and examples on how we use GraphQL docstrings for documenting core features and functions in the api, follow the [link](https://github.com/qctrl/api2#writing-documentation-for-co
I've removed the section referencing the private repository, as it does seem a bit odd to that on a public repo.

2020-09-16 08:05 UTC, charmasaur submitted a review, later dismissed

2020-09-16 23:33 UTC, robertlove requested changes

2020-09-16 23:33 UTC, robertlove commented on CONTRIBUTING.md
> +| GraphQL    | [GraphQL Rules](https://graphql-rules.com/)              | [CommonMark](https://commonmark.org/)[[++](#GraphQL-docstrings)] | N/A
@TabishB URI fragments should be lowercase (e.g. `#graphql-docstrings`, not `#GraphQL-docstrings`)

2020-09-17 01:32 UTC, robertlove approved these changes

2020-09-17 01:33 UTC, merged